<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <PropertyGroup>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <!--<CompilerGeneratedFilesOutputPath>$(ProjectDir)Generated</CompilerGeneratedFilesOutputPath>-->
  </PropertyGroup>
  <Target Name="SkipSourceGeneratedFiles" BeforeTargets="CoreCompile">
    <ItemGroup>
      <Compile Remove="Generated/**/*" />
    </ItemGroup>
  </Target>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.ObjectPool" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DotNetCompose.Runtime\DotNetCompose.Runtime.csproj" />
    <ProjectReference Include="..\DotNetCompose.SourceGenerators\DotNetCompose.SourceGenerators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />

  </ItemGroup>


</Project>
